/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as ChiefRouteImport } from './routes/chief'
import { Route as DisplayJoinRouteImport } from './routes/display-join'
import { Route as JudgeRouteImport } from './routes/judge'
import { Route as JudgeARouteImport } from './routes/judge-a'
import { Route as JudgeBRouteImport } from './routes/judge-b'
import { Route as JudgeCRouteImport } from './routes/judge-c'
import { Route as JudgeJoinRouteImport } from './routes/judge-join'
import { Route as PublicDisplayRouteImport } from './routes/public-display'
import { Route as ScoreboardRouteImport } from './routes/scoreboard'
import { Route as TaRouteImport } from './routes/ta'
import { Route as VarReviewRouteImport } from './routes/var-review'
import { Route as AthleteReportIdRouteImport } from './routes/athlete-report.$id'
import { Route as PublicReportIdRouteImport } from './routes/public-report.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const ChiefRoute = ChiefRouteImport.update({
  id: '/chief',
  path: '/chief',
  getParentRoute: () => rootRouteImport,
} as any)
const DisplayJoinRoute = DisplayJoinRouteImport.update({
  id: '/display-join',
  path: '/display-join',
  getParentRoute: () => rootRouteImport,
} as any)
const JudgeRoute = JudgeRouteImport.update({
  id: '/judge',
  path: '/judge',
  getParentRoute: () => rootRouteImport,
} as any)
const JudgeARoute = JudgeARouteImport.update({
  id: '/judge-a',
  path: '/judge-a',
  getParentRoute: () => rootRouteImport,
} as any)
const JudgeBRoute = JudgeBRouteImport.update({
  id: '/judge-b',
  path: '/judge-b',
  getParentRoute: () => rootRouteImport,
} as any)
const JudgeCRoute = JudgeCRouteImport.update({
  id: '/judge-c',
  path: '/judge-c',
  getParentRoute: () => rootRouteImport,
} as any)
const JudgeJoinRoute = JudgeJoinRouteImport.update({
  id: '/judge-join',
  path: '/judge-join',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicDisplayRoute = PublicDisplayRouteImport.update({
  id: '/public-display',
  path: '/public-display',
  getParentRoute: () => rootRouteImport,
} as any)
const ScoreboardRoute = ScoreboardRouteImport.update({
  id: '/scoreboard',
  path: '/scoreboard',
  getParentRoute: () => rootRouteImport,
} as any)
const TaRoute = TaRouteImport.update({
  id: '/ta',
  path: '/ta',
  getParentRoute: () => rootRouteImport,
} as any)
const VarReviewRoute = VarReviewRouteImport.update({
  id: '/var-review',
  path: '/var-review',
  getParentRoute: () => rootRouteImport,
} as any)
const AthleteReportIdRoute = AthleteReportIdRouteImport.update({
  id: '/athlete-report/$id',
  path: '/athlete-report/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicReportIdRoute = PublicReportIdRouteImport.update({
  id: '/public-report/$id',
  path: '/public-report/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/chief': typeof ChiefRoute
  '/display-join': typeof DisplayJoinRoute
  '/judge': typeof JudgeRoute
  '/judge-a': typeof JudgeARoute
  '/judge-b': typeof JudgeBRoute
  '/judge-c': typeof JudgeCRoute
  '/judge-join': typeof JudgeJoinRoute
  '/public-display': typeof PublicDisplayRoute
  '/scoreboard': typeof ScoreboardRoute
  '/ta': typeof TaRoute
  '/var-review': typeof VarReviewRoute
  '/athlete-report/$id': typeof AthleteReportIdRoute
  '/public-report/$id': typeof PublicReportIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/chief': typeof ChiefRoute
  '/display-join': typeof DisplayJoinRoute
  '/judge': typeof JudgeRoute
  '/judge-a': typeof JudgeARoute
  '/judge-b': typeof JudgeBRoute
  '/judge-c': typeof JudgeCRoute
  '/judge-join': typeof JudgeJoinRoute
  '/public-display': typeof PublicDisplayRoute
  '/scoreboard': typeof ScoreboardRoute
  '/ta': typeof TaRoute
  '/var-review': typeof VarReviewRoute
  '/athlete-report/$id': typeof AthleteReportIdRoute
  '/public-report/$id': typeof PublicReportIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/chief': typeof ChiefRoute
  '/display-join': typeof DisplayJoinRoute
  '/judge': typeof JudgeRoute
  '/judge-a': typeof JudgeARoute
  '/judge-b': typeof JudgeBRoute
  '/judge-c': typeof JudgeCRoute
  '/judge-join': typeof JudgeJoinRoute
  '/public-display': typeof PublicDisplayRoute
  '/scoreboard': typeof ScoreboardRoute
  '/ta': typeof TaRoute
  '/var-review': typeof VarReviewRoute
  '/athlete-report/$id': typeof AthleteReportIdRoute
  '/public-report/$id': typeof PublicReportIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assistant'
    | '/chief'
    | '/display-join'
    | '/judge'
    | '/judge-a'
    | '/judge-b'
    | '/judge-c'
    | '/judge-join'
    | '/public-display'
    | '/scoreboard'
    | '/ta'
    | '/var-review'
    | '/athlete-report/$id'
    | '/public-report/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assistant'
    | '/chief'
    | '/display-join'
    | '/judge'
    | '/judge-a'
    | '/judge-b'
    | '/judge-c'
    | '/judge-join'
    | '/public-display'
    | '/scoreboard'
    | '/ta'
    | '/var-review'
    | '/athlete-report/$id'
    | '/public-report/$id'
  id:
    | '__root__'
    | '/'
    | '/assistant'
    | '/chief'
    | '/display-join'
    | '/judge'
    | '/judge-a'
    | '/judge-b'
    | '/judge-c'
    | '/judge-join'
    | '/public-display'
    | '/scoreboard'
    | '/ta'
    | '/var-review'
    | '/athlete-report/$id'
    | '/public-report/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssistantRoute: typeof AssistantRoute
  ChiefRoute: typeof ChiefRoute
  DisplayJoinRoute: typeof DisplayJoinRoute
  JudgeRoute: typeof JudgeRoute
  JudgeARoute: typeof JudgeARoute
  JudgeBRoute: typeof JudgeBRoute
  JudgeCRoute: typeof JudgeCRoute
  JudgeJoinRoute: typeof JudgeJoinRoute
  PublicDisplayRoute: typeof PublicDisplayRoute
  ScoreboardRoute: typeof ScoreboardRoute
  TaRoute: typeof TaRoute
  VarReviewRoute: typeof VarReviewRoute
  AthleteReportIdRoute: typeof AthleteReportIdRoute
  PublicReportIdRoute: typeof PublicReportIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chief': {
      id: '/chief'
      path: '/chief'
      fullPath: '/chief'
      preLoaderRoute: typeof ChiefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/display-join': {
      id: '/display-join'
      path: '/display-join'
      fullPath: '/display-join'
      preLoaderRoute: typeof DisplayJoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/judge': {
      id: '/judge'
      path: '/judge'
      fullPath: '/judge'
      preLoaderRoute: typeof JudgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/judge-a': {
      id: '/judge-a'
      path: '/judge-a'
      fullPath: '/judge-a'
      preLoaderRoute: typeof JudgeARouteImport
      parentRoute: typeof rootRouteImport
    }
    '/judge-b': {
      id: '/judge-b'
      path: '/judge-b'
      fullPath: '/judge-b'
      preLoaderRoute: typeof JudgeBRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/judge-c': {
      id: '/judge-c'
      path: '/judge-c'
      fullPath: '/judge-c'
      preLoaderRoute: typeof JudgeCRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/judge-join': {
      id: '/judge-join'
      path: '/judge-join'
      fullPath: '/judge-join'
      preLoaderRoute: typeof JudgeJoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/public-display': {
      id: '/public-display'
      path: '/public-display'
      fullPath: '/public-display'
      preLoaderRoute: typeof PublicDisplayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scoreboard': {
      id: '/scoreboard'
      path: '/scoreboard'
      fullPath: '/scoreboard'
      preLoaderRoute: typeof ScoreboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ta': {
      id: '/ta'
      path: '/ta'
      fullPath: '/ta'
      preLoaderRoute: typeof TaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/var-review': {
      id: '/var-review'
      path: '/var-review'
      fullPath: '/var-review'
      preLoaderRoute: typeof VarReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/athlete-report/$id': {
      id: '/athlete-report/$id'
      path: '/athlete-report/$id'
      fullPath: '/athlete-report/$id'
      preLoaderRoute: typeof AthleteReportIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/public-report/$id': {
      id: '/public-report/$id'
      path: '/public-report/$id'
      fullPath: '/public-report/$id'
      preLoaderRoute: typeof PublicReportIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssistantRoute: AssistantRoute,
  ChiefRoute: ChiefRoute,
  DisplayJoinRoute: DisplayJoinRoute,
  JudgeRoute: JudgeRoute,
  JudgeARoute: JudgeARoute,
  JudgeBRoute: JudgeBRoute,
  JudgeCRoute: JudgeCRoute,
  JudgeJoinRoute: JudgeJoinRoute,
  PublicDisplayRoute: PublicDisplayRoute,
  ScoreboardRoute: ScoreboardRoute,
  TaRoute: TaRoute,
  VarReviewRoute: VarReviewRoute,
  AthleteReportIdRoute: AthleteReportIdRoute,
  PublicReportIdRoute: PublicReportIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
